# This file is generated by Anlogic Timing Wizard. 11 05 2020

#Created Clock
create_clock -name byte_clk -period 8.9 -waveform {0 4.45} [get_ports {byte_clk}]
create_clock -name ctrl_clk -period 6.7 -waveform {0 3.35} [get_ports {ctrl_clk}]

#Set Clock Groups
set_clock_groups -exclusive -group [get_clocks {byte_clk}] -group [get_clocks {ctrl_clk}]

